import type { NextPage } from "next";
import Head from "next/head";
import Header from "./layout/header";
import Emp from "./emp";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="max-w-7xl mx-auto px-4 sm:px-6">
        <Emp />
      </div>
    </div>
  );
};

export default Home;
